---
- name: Configure App servers for the application
  hosts: app
  become: true

  roles:
    - app
    - jdauphant.nginx

  tasks:
    - name: Debug msg
      debug:
        msg: "deploy user is {{ deploy_user }}"
