---
- name: Deploy the application on App server
  hosts: app
  become: true
  tags: deploy-app
  tasks:

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/shma/reddit
        version: monolith

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/shma/reddit

