# tasks file for app
  - name: Show current environment this host belongs to
    debug:
      msg: "This host is in {{ env }} environment"

  - name: Add config for DB connection
    template:
      src: db_config.j2
      dest: /home/shma/db_config
      owner: shma
      group: shma

  - name: Add unit file for Puma
    copy:
      src: puma.service
      dest: /etc/systemd/system/puma.service
    notify: Restart puma service

  - name: Enable puma service
    systemd: name=puma enabled=yes


